### ISSUE TITLE
[Question] Prometheus 如何正确配置和数据同步状态的正常采集并显示（读和写）

### ISSUE THREAD

**Issue by caiyuyux** [DTStack/Taier#1007]
### Search before asking

- [X] I had searched in the [issues](https://github.com/DTStack/Taier/issues) and found no similar question.

- [X] I had searched my question on the internet but i didn't get any help.

- [X] I had read the documentation: [Taier doc](https://dtstack.github.io/Taier) but it didn't help me.

### Description

1、在集群管理的 Prometheus 和 Promgateway 相关的配置项该如何配置呢？
2、完成配置如果发现没有达到预期，比如控制台显示的读取和写入记录数量为 0 ，该怎么办呢？
![image](https://user-images.githubusercontent.com/8185717/225223909-de0b26ad-bd36-40d3-91ee-3fd0f41f86d8.png)

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

**Comment by caiyuyux** [comment]
分享一下我的解决经验。
1. Prometheus 和 Promgateway 先需要另外部署。可以参考 [这个](https://www.cnblogs.com/evescn/p/12843653.html)
```
--- docker-compose.yml ---
version: "3"
services:
  pushgateway:
    image: prom/pushgateway:v0.4.0
    command: --persistence.file=/pushgateway/pushgateway.data
    ports:
      - 9091:9091
    volumes:
      - ./data/pushgateway:/pushgateway
  prometheus:
    #image: prom/prometheus:v2.0.0
    image: prom/prometheus:v2.18.1
    command: --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.retention=60d
    user: 0:0
    ports:
      - 9190:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alerts/:/etc/prometheus/rules.d/
      - ./data/prometheus:/prometheus
  grafana:
    #image: grafana/grafana:4.6.2
    image: grafana/grafana:6.7.1
    ports:
      - 3000:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
```
```
--- prometheus.yml --
global:
  scrape_interval:     15s # 默认抓取周期
  external_labels:
    monitor: 'codelab-monitor'
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'pushgateway'
    static_configs:
    - targets: ['192.168.1.121:9091']
      labels:
        instance: 'pushgateway'
  - job_name: prometheus
    static_configs:
    - targets: ['192.168.1.121:9190']
      labels:
        instance: prometheus
```

![image](https://user-images.githubusercontent.com/8185717/225224974-c8521b9d-a3d2-4835-a7a2-98797e448e15.png)
![image](https://user-images.githubusercontent.com/8185717/225225015-77e78b93-36d3-44b8-bbad-5b9c9083b247.png)

2. 此时部署完成，运行 preJob 任务是可以正常显示效果
![image](https://user-images.githubusercontent.com/8185717/225225194-68b1c538-fee1-4966-8242-e1b5fcff27a5.png)

但是 session 任务还是不行。

根据 偷天大佬的建议，排查了一遍，到 prometheus ui 和 pushgateway ui 看了下。
我这边的情况是跑 session 任务的时候 Prometheus 没有拉到数据，符合第二种情况。
![image](https://user-images.githubusercontent.com/8185717/225225450-a74eebfd-2967-479a-97b0-788f38864b1e.png)

在 yarn 上把 session 杀掉，重启 taier，再跑一遍就正常了。
