### ISSUE TITLE
docker部署，前端接口报错 502

### ISSUE THREAD

**Issue by YashonNice** [DTStack/Taier#510]
### docker 配置 （版本：1.10）
```yaml
version: '3'
services:
  taier-db:
    image: dtopensource/taier-mysql:1.10
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: taier
      MYSQL_ROOT_PASSWORD: 123456
  taier-zk:
    image: zookeeper:3.4.9
  taier-ui:
    image: dtopensource/taier-ui:1.10
    ports:
      - 80:80
    environment:
      TAIER_IP: taier
  taier:
    image: dtopensource/taier:1.10
    ports:
      - 8090:8090
    environment:
      NODE_ZKADDRESS: taier-zk
      MYSQL_IP: taier-db
```
![微信图片_20220524112125](https://user-images.githubusercontent.com/41532329/169942853-4786b2f7-ae3a-4328-aa83-001c0d4dd8fa.png)
